CREATE TABLE IF NOT EXISTS `pinba`.`stats` (
  `uptime` double NOT NULL,
  `ru_utime` double NOT NULL,
  `ru_stime` double NOT NULL,
  `udp_poll_total` bigint(20) unsigned NOT NULL,
  `udp_recv_total` bigint(20) unsigned NOT NULL,
  `udp_recv_eagain` bigint(20) unsigned NOT NULL,
  `udp_recv_bytes` bigint(20) unsigned NOT NULL,
  `udp_recv_packets` bigint(20) unsigned NOT NULL,
  `udp_packet_decode_err` bigint(20) unsigned NOT NULL,
  `udp_batch_send_total` bigint(20) unsigned NOT NULL,
  `udp_batch_send_err` bigint(20) unsigned NOT NULL,
  `udp_packet_send_total` bigint(20) unsigned NOT NULL,
  `udp_packet_send_err` bigint(20) unsigned NOT NULL,
  `udp_ru_utime` double NOT NULL,
  `udp_ru_stime` double NOT NULL,
  `repacker_poll_total` bigint(20) unsigned NOT NULL,
  `repacker_recv_total` bigint(20) unsigned NOT NULL,
  `repacker_recv_eagain` bigint(20) unsigned NOT NULL,
  `repacker_recv_packets` bigint(20) unsigned NOT NULL,
  `repacker_packet_validate_err` bigint(20) unsigned NOT NULL,
  `repacker_batch_send_total` bigint(20) unsigned NOT NULL,
  `repacker_batch_send_by_timer` bigint(20) unsigned NOT NULL,
  `repacker_batch_send_by_size` bigint(20) unsigned NOT NULL,
  `repacker_ru_utime` double NOT NULL,
  `repacker_ru_stime` double NOT NULL,
  `coordinator_batches_received` bigint(20) unsigned NOT NULL,
  `coordinator_batch_send_total` bigint(20) unsigned NOT NULL,
  `coordinator_batch_send_err` bigint(20) unsigned NOT NULL,
  `coordinator_control_requests` bigint(20) unsigned NOT NULL,
  `coordinator_ru_utime` double NOT NULL,
  `coordinator_ru_stime` double NOT NULL,
  `dictionary_size` bigint(20) unsigned NOT NULL,
  `dictionary_mem_hash` bigint(20) unsigned NOT NULL,
  `dictionary_mem_list` bigint(20) unsigned NOT NULL,
  `dictionary_mem_strings` bigint(20) unsigned NOT NULL,
  `version_info` text NOT NULL,
  `build_string` text NOT NULL
) ENGINE=PINBA DEFAULT CHARSET=latin1 COMMENT='v2/stats';
